# 심장질환

## 데이터 불러오기

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('./data/brfss.csv')
df.shape

(438693, 14)

## 데이터 전처리

In [390]:
df.dtypes #https://jimmy-ai.tistory.com/95

HEARTDISEASE    float64
SEX               int64
HEIGHT          float64
WEIGHT          float64
BLIND           float64
DEAF            float64
DIABETE         float64
CHOLESTEROL     float64
HYPERTENSION    float64
KIDNEY          float64
LIVER1          float64
LIVER2          float64
ALCOHOL         float64
SMOKE           float64
dtype: object

In [391]:
display(df.head())
display(df.tail())

HEARTDISEASE  SEX  HEIGHT  WEIGHT  BLIND  DEAF  DIABETE  CHOLESTEROL  \
0           2.0    2   411.0    72.0    2.0   2.0      3.0          1.0   
1           2.0    2   506.0  7777.0    1.0   2.0      1.0          1.0   
2           2.0    2   505.0   170.0    2.0   2.0      1.0          2.0   
3           2.0    2   504.0   195.0    2.0   2.0      1.0          1.0   
4           1.0    1   511.0   206.0    2.0   1.0      1.0          1.0   

   HYPERTENSION  KIDNEY  LIVER1  LIVER2  ALCOHOL  SMOKE  
0           3.0     2.0     NaN     NaN    888.0    1.0  
1           1.0     1.0     NaN     NaN    888.0    2.0  
2           1.0     2.0     NaN     NaN    888.0    2.0  
3           1.0     2.0     NaN     NaN    101.0    2.0  
4           4.0     2.0     NaN     NaN    888.0    2.0

HEARTDISEASE  SEX  HEIGHT  WEIGHT  BLIND  DEAF  DIABETE  CHOLESTEROL  \
438688           2.0    2   502.0   135.0    2.0   2.0      2.0          2.0   
438689           2.0    1   502.0  9999.0    1.0   2.0      1.0          2.0   
438690           2.0    1   511.0   220.0    2.0   2.0      3.0          1.0   
438691           2.0    1   600.0   175.0    2.0   2.0      3.0          2.0   
438692           2.0    2   503.0   179.0    2.0   2.0      3.0          1.0   

        HYPERTENSION  KIDNEY  LIVER1  LIVER2  ALCOHOL  SMOKE  
438688           1.0     2.0     NaN     NaN    204.0    1.0  
438689           1.0     2.0     NaN     NaN    888.0    2.0  
438690           3.0     2.0     NaN     NaN    210.0    2.0  
438691           1.0     2.0     NaN     NaN    203.0    2.0  
438692           3.0     2.0     NaN     NaN    201.0    2.0

### 성별값 1, 2를 M, F로 변환

In [392]:
df['SEX'].unique()

array([2, 1], dtype=int64)

In [393]:
type = {1:'M', 2:'F'} #1은 'M'으로, 2는 'F'로 변경
df['SEX'].replace(type, inplace=True) #inplace=True로 원본객체 변경
df['SEX'].unique()

array(['F', 'M'], dtype=object)

### 키(HEIGHT)열의 원소들 피트, 인치값을 cm값으로 모두 변환

#### 심장질환데이터(brfss.csv)에서는 3자리수대가 100의 자리가 feet, 10과 1의 자리가 inch / 9061~9998은 cm단위 / 7777은 모르거나 확신하지 못함 / 9999는 답변을 거부 / NAN은 묻지 않았거나 데이터가 소실되었다는 뜻)

In [394]:
#df['HEIGHT'] = df['HEIGHT'].astype(int)

In [395]:
print(df['HEIGHT'].isnull().sum()) #결측치 개수 확인

12959


In [396]:
df['HEIGHT'].unique()

array([ 411.,  506.,  505.,  504.,  511.,  603.,  600.,  509.,  503.,
        410.,  510.,  500.,  502.,   nan,  602.,  601.,  507., 9999.,
        508.,  501.,  604.,  605., 7777.,  609.,  606.,  409.,  407.,
        405.,  408.,  607.,  702.,  401.,  608.,  406.,  400., 9180.,
       9155.,  701.,  704., 9182.,  611.,  311.,  706., 9151., 9152.,
       9160., 9177., 9164., 9162., 9156., 9165., 9150., 9178., 9190.,
       9175., 9170., 9185., 9183., 9153., 9169., 9168., 9167., 9172.,
       9166., 9140., 9106., 9143., 9171., 9154., 9176., 9200., 9188.,
       9146., 9148., 9158., 9159., 9187.,  305.,  300., 9205.,  306.,
       9206., 9173., 9120.,  705.,  700.,  302., 9157., 9184., 9163.,
       9174., 9125.,  402.,  708.,  403.,  308.,  404., 9105.,  703.,
       9145., 9181., 9186.,  711.,  610., 9149., 9138., 9195., 9096.,
       9103., 9135., 9197., 9189., 9090., 9161., 9198., 9136., 9118.,
        301., 9134., 9144., 9147., 9179.,  310.,  307., 9127., 9192.,
        309., 9100.,

In [397]:
print(df['HEIGHT'].head())
print(df['HEIGHT'].tail())

0    411.0
1    506.0
2    505.0
3    504.0
4    511.0
Name: HEIGHT, dtype: float64
438688    502.0
438689    502.0
438690    511.0
438691    600.0
438692    503.0
Name: HEIGHT, dtype: float64


In [398]:
index_number = df['HEIGHT'] == 7777 #index_number는 True나 False
print(index_number)

0         False
1         False
2         False
3         False
4         False
          ...  
438688    False
438689    False
438690    False
438691    False
438692    False
Name: HEIGHT, Length: 438693, dtype: bool


In [399]:
df.HEIGHT[index_number] #index_number가 True인 경우 출력

217       7777.0
423       7777.0
455       7777.0
620       7777.0
630       7777.0
           ...  
438420    7777.0
438430    7777.0
438467    7777.0
438473    7777.0
438531    7777.0
Name: HEIGHT, Length: 4094, dtype: float64

In [400]:
df.HEIGHT[index_number] = np.nan
df.HEIGHT[index_number]

C:\Users\sdh\AppData\Local\Temp\ipykernel_21948\2572194359.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.HEIGHT[index_number] = np.nan


217      NaN
423      NaN
455      NaN
620      NaN
630      NaN
          ..
438420   NaN
438430   NaN
438467   NaN
438473   NaN
438531   NaN
Name: HEIGHT, Length: 4094, dtype: float64

In [401]:
df.HEIGHT[df['HEIGHT'] == 9999] #값이 9999인 경우 출력

51        9999.0
90        9999.0
329       9999.0
382       9999.0
734       9999.0
           ...  
438194    9999.0
438254    9999.0
438425    9999.0
438479    9999.0
438594    9999.0
Name: HEIGHT, Length: 7506, dtype: float64

In [402]:
df.HEIGHT[df['HEIGHT'] == 9999] = np.nan #replace()로도 가능
print(df['HEIGHT'].unique())

[ 411.  506.  505.  504.  511.  603.  600.  509.  503.  410.  510.  500.
  502.   nan  602.  601.  507.  508.  501.  604.  605.  609.  606.  409.
  407.  405.  408.  607.  702.  401.  608.  406.  400. 9180. 9155.  701.
  704. 9182.  611.  311.  706. 9151. 9152. 9160. 9177. 9164. 9162. 9156.
 9165. 9150. 9178. 9190. 9175. 9170. 9185. 9183. 9153. 9169. 9168. 9167.
 9172. 9166. 9140. 9106. 9143. 9171. 9154. 9176. 9200. 9188. 9146. 9148.
 9158. 9159. 9187.  305.  300. 9205.  306. 9206. 9173. 9120.  705.  700.
  302. 9157. 9184. 9163. 9174. 9125.  402.  708.  403.  308.  404. 9105.
  703. 9145. 9181. 9186.  711.  610. 9149. 9138. 9195. 9096. 9103. 9135.
 9197. 9189. 9090. 9161. 9198. 9136. 9118.  301. 9134. 9144. 9147. 9179.
  310.  307. 9127. 9192.  309. 9100. 9130. 9194. 9132. 9117.  304.  303.
 9108. 9139. 9104. 9204. 9107. 9102. 9110. 9115. 9199.]


C:\Users\sdh\AppData\Local\Temp\ipykernel_21948\2084706850.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.HEIGHT[df['HEIGHT'] == 9999] = np.nan #replace()로도 가능


In [403]:
index_number = df['HEIGHT'] < 1000 #피트와 인치법으로 키를 측정한 사람들인지 아닌지(True면 피트와 인치법)
index_number

0         True
1         True
2         True
3         True
4         True
          ... 
438688    True
438689    True
438690    True
438691    True
438692    True
Name: HEIGHT, Length: 438693, dtype: bool

In [404]:
ft = df.HEIGHT[index_number]//100 #앞에 한 자리는 피트 값
ft

0         4.0
1         5.0
2         5.0
3         5.0
4         5.0
         ... 
438688    5.0
438689    5.0
438690    5.0
438691    6.0
438692    5.0
Name: HEIGHT, Length: 411543, dtype: float64

In [405]:
inch = df.HEIGHT[index_number]%100 #뒤에 두 자리는 인치값
inch

0         11.0
1          6.0
2          5.0
3          4.0
4         11.0
          ... 
438688     2.0
438689     2.0
438690    11.0
438691     0.0
438692     3.0
Name: HEIGHT, Length: 411543, dtype: float64

In [406]:
df.HEIGHT[index_number] = ft*30.48+inch*2.54 #피트와 인치를 cm값으로 변경 #https://www.rapidtables.org/ko/convert/length/feet-inch-to-cm.html
print(df['HEIGHT'])

0         149.86
1         167.64
2         165.10
3         162.56
4         180.34
           ...  
438688    157.48
438689    157.48
438690    180.34
438691    182.88
438692    160.02
Name: HEIGHT, Length: 438693, dtype: float64


C:\Users\sdh\AppData\Local\Temp\ipykernel_21948\245011458.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.HEIGHT[index_number] = ft*30.48+inch*2.54 #피트와 인치를 cm값으로 변경 #https://www.rapidtables.org/ko/convert/length/feet-inch-to-cm.html


In [407]:
index_number = df['HEIGHT'] > 9000 #남은 4자리 수는 cm법으로 키를 표기한 사람들.(9061~9998)
index_number

0         False
1         False
2         False
3         False
4         False
          ...  
438688    False
438689    False
438690    False
438691    False
438692    False
Name: HEIGHT, Length: 438693, dtype: bool

In [408]:
cm = df.HEIGHT[index_number]%9000 #맨 앞의 9는 metric value라는 뜻으로 붙인 것이므로 빼고 계산
cm

3814      180.0
3999      155.0
5338      182.0
10642     180.0
10858     151.0
          ...  
431886    164.0
432322    161.0
432843    177.0
433192    167.0
435887    152.0
Name: HEIGHT, Length: 2591, dtype: float64

In [409]:
df.HEIGHT[index_number] = cm

C:\Users\sdh\AppData\Local\Temp\ipykernel_21948\2909654864.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.HEIGHT[index_number] = cm


In [410]:
print(df['HEIGHT'].unique())

[149.86 167.64 165.1  162.56 180.34 190.5  182.88 175.26 160.02 147.32
 177.8  152.4  157.48    nan 187.96 185.42 170.18 172.72 154.94 193.04
 195.58 205.74 198.12 144.78 139.7  134.62 142.24 200.66 218.44 124.46
 203.2  137.16 121.92 180.   155.   215.9  223.52 182.   210.82 119.38
 228.6  151.   152.   160.   177.   164.   162.   156.   165.   150.
 178.   190.   175.   170.   185.   183.   153.   169.   168.   167.
 172.   166.   140.   106.   143.   171.   154.   176.   200.   188.
 146.   148.   158.   159.   187.   104.14  91.44 205.   106.68 206.
 173.   120.   226.06 213.36  96.52 157.   184.   163.   174.   125.
 127.   233.68 129.54 111.76 132.08 105.   220.98 145.   181.   186.
 241.3  208.28 149.   138.   195.    96.   103.   135.   197.   189.
  90.   161.   198.   136.   118.    93.98 134.   144.   147.   179.
 116.84 109.22 192.   114.3  100.   130.   194.   132.   117.   101.6
  99.06 108.   139.   104.   204.   107.   102.   110.   115.   199.  ]


In [411]:
print(df['HEIGHT'].head())
print(df['HEIGHT'].tail())

0    149.86
1    167.64
2    165.10
3    162.56
4    180.34
Name: HEIGHT, dtype: float64
438688    157.48
438689    157.48
438690    180.34
438691    182.88
438692    160.02
Name: HEIGHT, dtype: float64


### 몸무게(WEIGHT)열 값들 파운드에서 kg으로 모두 변환

#### 심장질환데이터(brfss.csv)에서는 3자리수대가 파운드 / 9023~9352은 kg / 7777은 모르거나 확신하지 못함 / 9999는 답변을 거부 / NAN은 묻지 않았거나 데이터가 소실되었다는 뜻)

In [412]:
df['WEIGHT'].unique()

array([  72., 7777.,  170.,  195.,  206.,  340.,  154.,  240.,  160.,
        134.,  202.,  165., 9999.,  104.,  162.,  200.,  185.,  150.,
        250.,  115.,  256.,  220.,  180.,  230.,  175.,  123.,  275.,
        179.,  155.,   nan,  248.,  325.,  187.,  225.,  215.,  142.,
        208.,  145.,  135.,  194.,  265.,  110.,  188.,  153.,  137.,
        198.,  147.,  190.,  159.,  193.,  138.,  167.,  196.,  203.,
        125.,  176.,  140.,  130.,  122.,  253.,  100.,  163.,  120.,
        148.,  276.,  171.,  212.,  210.,  255.,  182.,  300.,  174.,
        156.,  211.,  118.,  192.,  183.,  272.,  218.,  161.,  169.,
        178.,  151.,  158.,  184.,  270.,  143.,  128.,  164.,  181.,
        105.,  219.,  189.,  239.,  201.,  127.,  139.,  101.,   98.,
        260.,  237.,  280.,  235.,  238.,  197.,  205.,  117.,  172.,
        289.,  216.,  186.,  245.,  112.,  126.,  177.,  168.,  252.,
        144.,  214.,  149.,  166.,  233.,  244.,  191.,  152.,  113.,
        136.,  236.,

In [413]:
type = {7777:np.nan, 9999:np.nan} #777과 999는 NAN으로 변경
df['WEIGHT'].replace(type, inplace=True) #inplace=True로 원본객체 변경
df['WEIGHT'].unique()

array([  72.,   nan,  170.,  195.,  206.,  340.,  154.,  240.,  160.,
        134.,  202.,  165.,  104.,  162.,  200.,  185.,  150.,  250.,
        115.,  256.,  220.,  180.,  230.,  175.,  123.,  275.,  179.,
        155.,  248.,  325.,  187.,  225.,  215.,  142.,  208.,  145.,
        135.,  194.,  265.,  110.,  188.,  153.,  137.,  198.,  147.,
        190.,  159.,  193.,  138.,  167.,  196.,  203.,  125.,  176.,
        140.,  130.,  122.,  253.,  100.,  163.,  120.,  148.,  276.,
        171.,  212.,  210.,  255.,  182.,  300.,  174.,  156.,  211.,
        118.,  192.,  183.,  272.,  218.,  161.,  169.,  178.,  151.,
        158.,  184.,  270.,  143.,  128.,  164.,  181.,  105.,  219.,
        189.,  239.,  201.,  127.,  139.,  101.,   98.,  260.,  237.,
        280.,  235.,  238.,  197.,  205.,  117.,  172.,  289.,  216.,
        186.,  245.,  112.,  126.,  177.,  168.,  252.,  144.,  214.,
        149.,  166.,  233.,  244.,  191.,  152.,  113.,  136.,  236.,
         94.,   90.,

In [414]:
index_number = df['WEIGHT'] < 1000 #True일 경우 파운드로 몸무게가 기록된 사람들
index_number

0          True
1         False
2          True
3          True
4          True
          ...  
438688     True
438689    False
438690     True
438691     True
438692     True
Name: WEIGHT, Length: 438693, dtype: bool

In [415]:
df.WEIGHT[index_number] = df.WEIGHT[index_number]*0.45359237 #파운드를 kg로 변환
print(df.WEIGHT[index_number])

0         32.658651
2         77.110703
3         88.450512
4         93.440028
5         88.450512
            ...    
438687    69.853225
438688    61.234970
438690    99.790321
438691    79.378665
438692    81.193034
Name: WEIGHT, Length: 396734, dtype: float64


C:\Users\sdh\AppData\Local\Temp\ipykernel_21948\39705853.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.WEIGHT[index_number] = df.WEIGHT[index_number]*0.45359237 #파운드를 kg로 변환


In [416]:
index_number = df['WEIGHT'] > 9000 #True일 경우 kg로 몸무게가 기록된 사람들
df.WEIGHT[index_number] #kg으로 몸무게가 기록된 사람들 출력(맨 앞에 9는 kg이라는 뜻)

3814      9072.0
4484      9065.0
4571      9073.0
5338      9090.0
6570      9105.0
           ...  
433192    9063.0
433269    9062.0
437585    9050.0
438111    9060.0
438534    9075.0
Name: WEIGHT, Length: 1384, dtype: float64

In [417]:
df.WEIGHT[index_number] = df.WEIGHT[index_number]%9000 #맨 앞에 9는 kg단위라는 뜻이므로 9000으로 나눈 나머지를 계산
print(df.WEIGHT[index_number])

3814       72.0
4484       65.0
4571       73.0
5338       90.0
6570      105.0
          ...  
433192     63.0
433269     62.0
437585     50.0
438111     60.0
438534     75.0
Name: WEIGHT, Length: 1384, dtype: float64


C:\Users\sdh\AppData\Local\Temp\ipykernel_21948\1467237082.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.WEIGHT[index_number] = df.WEIGHT[index_number]%9000 #맨 앞에 9는 kg단위라는 뜻이므로 9000으로 나눈 나머지를 계산


In [418]:
df.WEIGHT.unique()

array([ 32.65865064,          nan,  77.1107029 ,  88.45051215,
        93.44002822, 154.2214058 ,  69.85322498, 108.8621688 ,
        72.5747792 ,  60.78137758,  91.62565874,  74.84274105,
        47.17360648,  73.48196394,  90.718474  ,  83.91458845,
        68.0388555 , 113.3980925 ,  52.16312255, 116.11964672,
        99.7903214 ,  81.6466266 , 104.3262451 ,  79.37866475,
        55.79186151, 124.73790175,  81.19303423,  70.30681735,
       112.49090776, 147.41752025,  84.82177319, 102.05828325,
        97.52235955,  64.41011654,  94.34721296,  65.77089365,
        61.23496995,  87.99691978, 120.20197805,  49.8951607 ,
        85.27536556,  69.39963261,  62.14215469,  89.81128926,
        66.67807839,  86.1825503 ,  72.12118683,  87.54332741,
        62.59574706,  75.74992579,  88.90410452,  92.07925111,
        56.69904625,  79.83225712,  63.5029318 ,  58.9670081 ,
        55.33826914, 114.75886961,  45.359237  ,  73.93555631,
        54.4310844 ,  67.13167076, 125.19149412,  77.56

### 음주 데이터(건강검진 데이터에서는 0: 마시지 않는다. 1:마신다.)
#### 심장질환데이터(brfss.csv)에서는 100번대가 매주 마신다 / 200번대는 달마다 마신다 / 777은 모른다 / 888은 지난 한달간 마시지 않았다. / 999는 답변을 거절했다. / NAN은 묻지 않았거나 데이터가 소실되었다는 뜻)

In [419]:
df['ALCOHOL'].unique()

array([888., 101., 203., 102., 999., 204., 230., 202., 103.,  nan, 201.,
       210., 205., 105., 217., 212., 104., 216., 777., 220., 206., 225.,
       107., 215., 207., 228., 209., 208., 106., 211., 229., 227., 214.,
       224., 221., 223., 218., 226., 222., 213., 219.])

In [420]:
print(df['ALCOHOL'].head())
print(df['ALCOHOL'].tail())

0    888.0
1    888.0
2    888.0
3    101.0
4    888.0
Name: ALCOHOL, dtype: float64
438688    204.0
438689    888.0
438690    210.0
438691    203.0
438692    201.0
Name: ALCOHOL, dtype: float64


In [421]:
type = {777:np.nan, 888: 0, 999:np.nan} #777과 999는 NAN으로 변경
df['ALCOHOL'].replace(type, inplace=True) #inplace=True로 원본객체 변경
df['ALCOHOL'].unique()

array([  0., 101., 203., 102.,  nan, 204., 230., 202., 103., 201., 210.,
       205., 105., 217., 212., 104., 216., 220., 206., 225., 107., 215.,
       207., 228., 209., 208., 106., 211., 229., 227., 214., 224., 221.,
       223., 218., 226., 222., 213., 219.])

In [422]:
index_number = (df['ALCOHOL'] > 100) & (df['ALCOHOL'] < 300) #술을 마신 사람들의 인덱스 정보 #https://stackoverflow.com/questions/22591174/pandas-multiple-conditions-while-indexing-data-frame-unexpected-behavior
index_number
## 아니면 아래처럼 하면 괄호 안 줘도 됨
#c1 = location_period["ccbaPcd1_item"].isnull()  # 시대가 결측값
#c2 = location_period["ccbaPcd1_item"] == "60"  # 시대가 미상
#c3 = location_period["ccbaPcd1_item"] == "00"  # 시대가 선사시대 이전
#c4 = location_period["longitude_item"] == "0"  # 경도가 결측값
#c5 = location_period["latitude_item"] == "0"  # 위도가 결측값
#condition = c1 | c2 | c3 | c4 | c5

0         False
1         False
2         False
3          True
4         False
          ...  
438688     True
438689    False
438690     True
438691     True
438692     True
Name: ALCOHOL, Length: 438693, dtype: bool

In [423]:
df.ALCOHOL[index_number] = 1 #술 마신 경우 데이터를 1을 저장
df.ALCOHOL.unique()

C:\Users\sdh\AppData\Local\Temp\ipykernel_21948\1135333750.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.ALCOHOL[index_number] = 1 #술 마신 경우 데이터를 1을 저장


array([ 0.,  1., nan])

In [424]:
print(df['ALCOHOL'].head())
print(df['ALCOHOL'].tail())

0    0.0
1    0.0
2    0.0
3    1.0
4    0.0
Name: ALCOHOL, dtype: float64
438688    1.0
438689    0.0
438690    1.0
438691    1.0
438692    1.0
Name: ALCOHOL, dtype: float64


### 흡연 여부(건강검진 데이터에서는 0: 피운 적 없다. 1:피운 적 있다.)
#### 심장질환데이터(brfss.csv)에서는 1: Yes / 2: No / 7: 모른다, 확신못함 / 9: 답변거절)

In [425]:
df['SMOKE'].unique()

array([ 1.,  2., nan,  7.,  9.])

In [426]:
print(df['SMOKE'].head())
print(df['SMOKE'].tail())

0    1.0
1    2.0
2    2.0
3    2.0
4    2.0
Name: SMOKE, dtype: float64
438688    1.0
438689    2.0
438690    2.0
438691    2.0
438692    2.0
Name: SMOKE, dtype: float64


In [427]:
type = {2:0, 7:np.nan, 9:np.nan} #2는 0으로, 7과 9는 NAN으로 변경
df['SMOKE'].replace(type, inplace=True) #inplace=True로 원본객체 변경
df['SMOKE'].unique()

array([ 1.,  0., nan])

In [428]:
print(df['SMOKE'].head())
print(df['SMOKE'].tail())

0    1.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: SMOKE, dtype: float64
438688    1.0
438689    0.0
438690    0.0
438691    0.0
438692    0.0
Name: SMOKE, dtype: float64


### 나머지 데이터들 값 변환

In [429]:
def replace_value(col, replace):
    print("="*10, col, "="*10)
    # before replacing
    print(df[col].value_counts())
    
    df[col].replace(replace, inplace=True)
    
    # after replacing
    print(df[col].value_counts())

In [430]:
# type1: BLIND, DEAF, KIDNEY, LIVER1, LIVER2, HEARTDISEASE
# 1 -> 1
# 2 -> 0
# 7, 9 -> np.nan
type1 = {1: 1, 2: 0, 7: np.nan, 9: np.nan}

replace_value("BLIND", type1)
replace_value("DEAF", type1)
replace_value("KIDNEY", type1)
replace_value("LIVER1", type1)
replace_value("LIVER2", type1)
replace_value("HEARTDISEASE", type1)

========== BLIND ==========
2.0    399597
1.0     21745
7.0       952
9.0       655
Name: BLIND, dtype: int64
0.0    399597
1.0     21745
Name: BLIND, dtype: int64
========== DEAF ==========
2.0    384717
1.0     37578
7.0      1113
9.0       683
Name: DEAF, dtype: int64
0.0    384717
1.0     37578
Name: DEAF, dtype: int64
========== KIDNEY ==========
2.0    419779
1.0     17101
7.0      1488
9.0       322
Name: KIDNEY, dtype: int64
0.0    419779
1.0     17101
Name: KIDNEY, dtype: int64
========== LIVER1 ==========
2.0    10580
1.0      163
7.0       48
9.0       13
Name: LIVER1, dtype: int64
0.0    10580
1.0      163
Name: LIVER1, dtype: int64
========== LIVER2 ==========
2.0    10602
1.0       95
7.0       63
9.0       19
Name: LIVER2, dtype: int64
0.0    10602
1.0       95
Name: LIVER2, dtype: int64
========== HEARTDISEASE ==========
2.0    413207
1.0     22831
7.0      2319
9.0       334
Name: HEARTDISEASE, dtype: int64
0.0    413207
1.0     22831
Name: HEARTDISEASE, dtype: int64


In [431]:
# type2: DIABETE, HYPERTENSION
# 1 -> 1
# 2, 3, 4 -> 0
# 7, 9 -> np.nan
type2 = {1: 1, 2: 0, 3: 0, 4: 0, 7: np.nan, 9: np.nan}

replace_value("DIABETE", type2)
replace_value("HYPERTENSION", type2)

========== DIABETE ==========
3.0    366342
1.0     57616
4.0      9942
2.0      3808
7.0       613
9.0       369
Name: DIABETE, dtype: int64
0.0    380092
1.0     57616
Name: DIABETE, dtype: int64
========== HYPERTENSION ==========
3.0    256603
1.0    172133
4.0      4571
2.0      3474
7.0      1191
9.0       719
Name: HYPERTENSION, dtype: int64
0.0    264648
1.0    172133
Name: HYPERTENSION, dtype: int64


### 데이터 변경 전체 확인

In [432]:
display(df.head())
display(df.tail())

HEARTDISEASE SEX  HEIGHT     WEIGHT  BLIND  DEAF  DIABETE  CHOLESTEROL  \
0           0.0   F  149.86  32.658651    0.0   0.0      0.0          1.0   
1           0.0   F  167.64        NaN    1.0   0.0      1.0          1.0   
2           0.0   F  165.10  77.110703    0.0   0.0      1.0          2.0   
3           0.0   F  162.56  88.450512    0.0   0.0      1.0          1.0   
4           1.0   M  180.34  93.440028    0.0   1.0      1.0          1.0   

   HYPERTENSION  KIDNEY  LIVER1  LIVER2  ALCOHOL  SMOKE  
0           0.0     0.0     NaN     NaN      0.0    1.0  
1           1.0     1.0     NaN     NaN      0.0    0.0  
2           1.0     0.0     NaN     NaN      0.0    0.0  
3           1.0     0.0     NaN     NaN      1.0    0.0  
4           0.0     0.0     NaN     NaN      0.0    0.0

HEARTDISEASE SEX  HEIGHT     WEIGHT  BLIND  DEAF  DIABETE  \
438688           0.0   F  157.48  61.234970    0.0   0.0      0.0   
438689           0.0   M  157.48        NaN    1.0   0.0      1.0   
438690           0.0   M  180.34  99.790321    0.0   0.0      0.0   
438691           0.0   M  182.88  79.378665    0.0   0.0      0.0   
438692           0.0   F  160.02  81.193034    0.0   0.0      0.0   

        CHOLESTEROL  HYPERTENSION  KIDNEY  LIVER1  LIVER2  ALCOHOL  SMOKE  
438688          2.0           1.0     0.0     NaN     NaN      1.0    1.0  
438689          2.0           1.0     0.0     NaN     NaN      0.0    0.0  
438690          1.0           0.0     0.0     NaN     NaN      1.0    0.0  
438691          2.0           1.0     0.0     NaN     NaN      1.0    0.0  
438692          1.0           0.0     0.0     NaN     NaN      1.0    0.0

## 수정한 데이터를 csv 파일로 저장

In [433]:
df.to_csv('./data/edit_brfss.csv', index=False) #https://velog.io/@holi/Pandas-Write-Files

# 건강검진정보

## 값 맞는지 확인

In [5]:
df = pd.read_csv('./data/region.csv')
display(df[['지역','심장혈관흉부외과의원']]) #지역별의원표시과목현황.xls와 비교

지역  심장혈관흉부외과의원
0       강원도         1.0
1       경기도         9.0
2      경상남도         2.0
3      경상북도         2.0
4     광주광역시         NaN
5     대구광역시         3.0
6     대전광역시         4.0
7     부산광역시         8.0
8     서울특별시        10.0
9   세종특별자치시         NaN
10    울산광역시         5.0
11    인천광역시         1.0
12     전라남도         2.0
13     전라북도         1.0
14  제주특별자치도         1.0
15     충청남도         4.0
16     충청북도         4.0

In [6]:
display(df[['지역','상급종합병원','종합병원','병원',]]) #지역별종별요양기관수현황.xls과 비교

지역  상급종합병원  종합병원   병원
0       강원도       2    13   37
1       경기도       5    62  277
2      경상남도       3    23  134
3      경상북도       0    20   55
4     광주광역시       2    21   84
5     대구광역시       5    13   88
6     대전광역시       1     9   46
7     부산광역시       3    25  136
8     서울특별시      14    42  222
9   세종특별자치시       0     2    1
10    울산광역시       1     8   33
11    인천광역시       3    17   56
12     전라남도       1    24   74
13     전라북도       2    11   64
14  제주특별자치도       0     6    7
15     충청남도       2    11   46
16     충청북도       1    12   37

## 데이터 불러오기

### 2020년 데이터

In [1]:
# API 키 불러오기
import json

with open("./secret.json", "r") as f:
    KEY = json.load(f)

In [10]:
import requests
from urllib import request
from bs4 import BeautifulSoup

import pandas as pd

API = "https://api.odcloud.kr/api/15007122/v1/uddi:95d6cbf2-f800-4ce3-a4f7-f57823274732?"

In [26]:
pageNum = 1
df = pd.DataFrame()

while True:
    print(f"page {pageNum}", end=" ")
    url = API + f"serviceKey={KEY['ENCODING']}&perPage={1000}&page={pageNum}"
    
    result = request.urlopen(url)
    soup = BeautifulSoup(result, "html.parser")
    json_data = json.loads(str(soup))
    
    if json_data["currentCount"] == 0:
        break
    
    df = pd.concat([df, pd.DataFrame(json_data["data"])], axis=0, ignore_index=True)
    
    pageNum = pageNum + 1
    
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   <html>  4 non-null      object
dtypes: object(1)
memory usage: 160.0+ bytes


### 2019년 데이터

In [ ]:
path = "SCR_2019_1백만20210119수정.csv"

# 의료 수준